#!/bin/bash
# Deployment helper script

echo "🚀 AI Research Assistant - Deployment Preparation"
echo "=================================================="
echo ""
echo "Step 1: Ensure all changes are committed to Git"
git status
echo ""
echo "Step 2: Push to GitHub"
echo "  Run: git push origin main"
echo ""
echo "Step 3: Backend Deployment (Render)"
echo "  1. Go to https://render.com/dashboard"
echo "  2. Click 'New +' → 'Web Service'"
echo "  3. Connect GitHub repository"
echo "  4. Select 'ai-research-assistant' repo"
echo ""
echo "  Fill in:"
echo "  - Name: ai-research-assistant-backend"
echo "  - Root Directory: backend"
echo "  - Build Command: pip install -r requirements.txt"
echo "  - Start Command: uvicorn app.main:app --host 0.0.0.0 --port 8000"
echo ""
echo "  Environment Variables:"
echo "  - OPENAI_API_KEY: (your API key, optional)"
echo ""
echo "Step 4: Get Backend URL"
echo "  After deploy completes, copy your backend URL"
echo "  Example: https://ai-research-assistant-backend.onrender.com"
echo ""
echo "Step 5: Update Frontend .env.production"
echo "  Edit frontend/.env.production"
echo "  Set: VITE_API_BASE_URL=<your-backend-url>"
echo ""
echo "Step 6: Commit and push changes"
echo "  git add frontend/.env.production"
echo "  git commit -m 'Add production backend URL'"
echo "  git push origin main"
echo ""
echo "Step 7: Frontend Deployment (Vercel)"
echo "  1. Go to https://vercel.com/dashboard"
echo "  2. Click 'Add New +' → 'Project'"
echo "  3. Import your GitHub repository"
echo "  4. Select 'ai-research-assistant' repo"
echo ""
echo "  Configuration:"
echo "  - Framework: React"
echo "  - Root Directory: frontend"
echo "  - Build Command: npm run build"
echo "  - Output Directory: dist"
echo ""
echo "  Environment Variables:"
echo "  - VITE_API_BASE_URL: <your-backend-url>"
echo ""
echo "Step 8: Deploy"
echo "  Click 'Deploy' and wait for completion"
echo ""
echo "Step 9: Update Backend CORS"
echo "  Edit backend/app/core/config.py"
echo "  Add your Vercel URL to BACKEND_CORS_ORIGINS"
echo "  Example: https://ai-research-assistant.vercel.app"
echo ""
echo "Step 10: Final Push"
echo "  git add backend/app/core/config.py"
echo "  git commit -m 'Add production frontend URL to CORS'"
echo "  git push origin main"
echo ""
echo "✅ Deployment should be complete!"
echo "=================================================="
